version: '3.3'
services:
  socks5:
    # image: socks5
    build:
      context: .
    restart: always
    ports:
      - '11080:1080'
    # environment:
    #   - USER=user
    #   - PASSWORD=mypassword
    env_file: .env
